name: chat
description: ''
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  peerdart: ^0.5.2
  permission_handler: ^11.1.0
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/icon.png"
flutter:
  uses-material-design: true
